/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { arbitersCreateChatCompletion } from "../funcs/arbiters-create-chat-completion.js";
import { arbitersGetSchema } from "../funcs/arbiters-get-schema.js";
import { arbitersGetSupportedModels } from "../funcs/arbiters-get-supported-models.js";
import { arbitersGet } from "../funcs/arbiters-get.js";
import { arbitersInit } from "../funcs/arbiters-init.js";
import { arbitersUpdateMetadata } from "../funcs/arbiters-update-metadata.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Arbiters extends ClientSDK {
  /**
   * Get Arbiter
   */
  async get(
    request: operations.GetArbiterApiV1ArbitersGetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(arbitersGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Arbiter Schema Output
   */
  async getSchema(
    request: operations.GetArbiterSchemaOutputApiV1ArbitersSchemaGetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(arbitersGetSchema(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Chat Completion
   */
  async createChatCompletion(
    request: models.ChatCompletionRequest,
    options?: RequestOptions,
  ): Promise<models.ChatCompletionResponse> {
    return unwrapAsync(arbitersCreateChatCompletion(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Supported Models
   */
  async getSupportedModels(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(arbitersGetSupportedModels(
      this,
      options,
    ));
  }

  /**
   * Init Arbiter
   */
  async init(
    request: models.InitArbiterRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(arbitersInit(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Arbiter Metadata
   *
   * @remarks
   * Patch YAML frontmatter metadata in the arbiter's README.md.
   */
  async updateMetadata(
    request: models.UpdateArbiterMetadataRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(arbitersUpdateMetadata(
      this,
      request,
      options,
    ));
  }
}
