/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chatCreateCompletion } from "../funcs/chat-create-completion.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Chat extends ClientSDK {
  /**
   * Create Chat Completion
   */
  async createCompletion(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(chatCreateCompletion(
      this,
      options,
    ));
  }
}
