/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { examplesDelete } from "../funcs/examples-delete.js";
import { examplesDownloadExport } from "../funcs/examples-download-export.js";
import { examplesExport } from "../funcs/examples-export.js";
import { examplesGetDistinctHashes } from "../funcs/examples-get-distinct-hashes.js";
import { examplesGetGradedCount } from "../funcs/examples-get-graded-count.js";
import { examplesGet } from "../funcs/examples-get.js";
import { examplesHasUncalibrated } from "../funcs/examples-has-uncalibrated.js";
import { examplesIngest } from "../funcs/examples-ingest.js";
import { examplesList } from "../funcs/examples-list.js";
import { examplesPatchAnnotation } from "../funcs/examples-patch-annotation.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Examples extends ClientSDK {
  /**
   * Ingest Examples
   */
  async ingest(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(examplesIngest(
      this,
      options,
    ));
  }

  /**
   * List Examples
   *
   * @remarks
   * Offset-based pagination for examples within a single repo, ordered by (created_at, id) ascending.
   */
  async list(
    request: operations.ListExamplesApiV1ExamplesGetRequest,
    options?: RequestOptions,
  ): Promise<models.PaginatedPage> {
    return unwrapAsync(examplesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Examples
   *
   * @remarks
   * Delete one or more examples from a repo.
   */
  async delete(
    request: models.DeleteExamplesRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(examplesDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Export Examples
   *
   * @remarks
   * Export a repo's latest prediction state as parquet and return a signed URL.
   */
  async export(
    request: models.ExportExamplesRequest,
    options?: RequestOptions,
  ): Promise<models.ExportExamplesResponse> {
    return unwrapAsync(examplesExport(
      this,
      request,
      options,
    ));
  }

  /**
   * Download Export
   *
   * @remarks
   * Stream an exported parquet file from S3.
   */
  async downloadExport(
    request: operations.DownloadExportApiV1ExamplesExportDownloadGetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(examplesDownloadExport(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Distinct Hashes
   *
   * @remarks
   * Return distinct arbiter_hash values for the repo's latest predictions.
   */
  async getDistinctHashes(
    request: operations.GetDistinctHashesApiV1ExamplesDistinctHashesGetRequest,
    options?: RequestOptions,
  ): Promise<Array<string>> {
    return unwrapAsync(examplesGetDistinctHashes(
      this,
      request,
      options,
    ));
  }

  /**
   * Has Uncalibrated Predictions
   *
   * @remarks
   * Check whether there are predictions without confidence scores.
   */
  async hasUncalibrated(
    request:
      operations.HasUncalibratedPredictionsApiV1ExamplesHasUncalibratedGetRequest,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(examplesHasUncalibrated(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Graded Count
   *
   * @remarks
   * Count predictions that have been graded (have ground truth).
   */
  async getGradedCount(
    request: operations.GetGradedCountApiV1ExamplesGradedCountGetRequest,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(examplesGetGradedCount(
      this,
      request,
      options,
    ));
  }

  /**
   * Patch Example
   *
   * @remarks
   * Updates an example annotation.
   */
  async patchAnnotation(
    request:
      operations.PatchExampleApiV1ExamplesExampleIdAnnotationPatchRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(examplesPatchAnnotation(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Example By Id
   */
  async get(
    request: operations.GetExampleByIdApiV1ExamplesExampleIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.PredictedExample> {
    return unwrapAsync(examplesGet(
      this,
      request,
      options,
    ));
  }
}
