/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { jobsCancelBatchPrediction } from "../funcs/jobs-cancel-batch-prediction.js";
import { jobsCancelConfidenceScore } from "../funcs/jobs-cancel-confidence-score.js";
import { jobsCancelOptimization } from "../funcs/jobs-cancel-optimization.js";
import { jobsGetBatchPredictionStatus } from "../funcs/jobs-get-batch-prediction-status.js";
import { jobsGetConfidenceScoreStatus } from "../funcs/jobs-get-confidence-score-status.js";
import { jobsGetOptimizationLogs } from "../funcs/jobs-get-optimization-logs.js";
import { jobsGetOptimizationStatus } from "../funcs/jobs-get-optimization-status.js";
import { jobsStartBatchPredictions } from "../funcs/jobs-start-batch-predictions.js";
import { jobsStartConfidenceScore } from "../funcs/jobs-start-confidence-score.js";
import { jobsStartOptimization } from "../funcs/jobs-start-optimization.js";
import { jobsStreamBatchEvents } from "../funcs/jobs-stream-batch-events.js";
import { jobsStreamBatchResults } from "../funcs/jobs-stream-batch-results.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Jobs extends ClientSDK {
  /**
   * Start Confidence Score Job
   *
   * @remarks
   * Start an async job to compute confidence scores for all predictions
   * with null confidence for the given repo.
   */
  async startConfidenceScore(
    request: models.ConfidenceScoreJobRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsStartConfidenceScore(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Confidence Score Job Status
   *
   * @remarks
   * Get the status of a confidence score computation job.
   */
  async getConfidenceScoreStatus(
    request:
      operations.GetConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsGetConfidenceScoreStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel Confidence Score Job
   *
   * @remarks
   * Cancel a running confidence score computation job.
   */
  async cancelConfidenceScore(
    request:
      operations.CancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsCancelConfidenceScore(
      this,
      request,
      options,
    ));
  }

  /**
   * Start Optimization Job
   *
   * @remarks
   * Start an async job to run GEPA optimization on an arbiter.
   * Uses annotated train/test predictions from ClickHouse to optimize the arbiter.
   * Runs in an isolated Modal Sandbox for clean cancellation support.
   *
   * The hub_jobs row is created *before* the sandbox starts so that the
   * sandbox always has a row to update with logs and terminal state.
   */
  async startOptimization(
    request: models.GepaJobRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsStartOptimization(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel Optimization Job
   *
   * @remarks
   * Cancel a running GEPA optimization job.
   *
   * Only cancels if the job is still in the ``optimizing`` phase.  If the
   * sandbox already reached a terminal state (``finalizing`` or ``done``),
   * the UPDATE is a no-op so we don't clobber a successful result or
   * interfere with the finalization pipeline.
   */
  async cancelOptimization(
    request: operations.CancelOptimizationJobApiV1JobsGepaJobIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsCancelOptimization(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Optimization Job Status
   *
   * @remarks
   * Get the status of a GEPA optimization job.
   *
   * This endpoint is a pure Postgres reader. The sandbox writes logs and
   * terminal state directly to the hub_jobs row; a background Celery task
   * handles finalization (env_var cleanup, Slack notification, re-predict
   * trigger). Subsequent re-predict/scoring phases are tracked via the
   * ``phase`` column updated by the Celery pipeline.
   */
  async getOptimizationStatus(
    request: operations.GetOptimizationJobStatusApiV1JobsGepaJobIdGetRequest,
    options?: RequestOptions,
  ): Promise<models.GepaJobResponse> {
    return unwrapAsync(jobsGetOptimizationStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Optimization Job Logs
   *
   * @remarks
   * Get logs from a GEPA optimization job.
   *
   * Logs are written directly to Postgres by the sandbox — this endpoint
   * is a pure reader.
   */
  async getOptimizationLogs(
    request: operations.GetOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsGetOptimizationLogs(
      this,
      request,
      options,
    ));
  }

  /**
   * Start Batch Predictions Job
   *
   * @remarks
   * Start an async batch prediction job.
   *
   * Two input modes (mutually exclusive):
   *
   * * ``examples`` — ingest brand-new examples and run predictions on them.
   * * ``example_ids`` — re-predict existing examples (referenced by their
   *   ClickHouse ids). Predictions are inserted as new versions on the
   *   existing example rows; no new examples rows are written.
   *
   * When ``compute_confidence=True`` the worker pre-warms a probe scorer
   * container per arbiter and, after predictions persist, kicks off Modal
   * batch confidence scoring filtered to the prediction_ids produced by
   * this job (so we don't accidentally re-score unrelated NULL-confidence
   * rows). Predictions are visible to clients during the scoring phase via
   * ``GET /results`` — confidence populates as Modal streams.
   *
   * Phases visible via ``GET /{job_id}`` and SSE: ``predicting → scoring →
   * done`` (or ``failed``).
   */
  async startBatchPredictions(
    request: models.BatchPredictionsJobRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsStartBatchPredictions(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Batch Predictions Job Status
   *
   * @remarks
   * Get the latest snapshot for a batch predictions job.
   *
   * Returns the same `BatchPredictionsEvent` shape SSE forwards (minus the
   * per-prediction payload). For the per-prediction list, use `GET /results`.
   *
   * Mapping:
   *   * Celery PROGRESS  → return the latest snapshot stored in `meta`.
   *   * Celery PENDING   → synthesize a zeroed `event="start"` snapshot.
   *   * Celery SUCCESS   → return the terminal `event="finish"` snapshot.
   *   * Celery FAILURE   → synthesize an `event="finish", status="failed"` dict.
   *   * Celery REVOKED   → synthesize an `event="finish", status="failed",
   *     error="cancelled"` dict.
   */
  async getBatchPredictionStatus(
    request:
      operations.GetBatchPredictionsJobStatusApiV1JobsBatchPredictionsJobIdGetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsGetBatchPredictionStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel Batch Predictions Job
   *
   * @remarks
   * Cancel a running batch predictions job. Because all inserts happen in a
   * single transaction at the end of the task, cancelling mid-execution leaves
   * no partial state in ClickHouse.
   */
  async cancelBatchPrediction(
    request:
      operations.CancelBatchPredictionsJobApiV1JobsBatchPredictionsJobIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsCancelBatchPrediction(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream Batch Predictions Events
   *
   * @remarks
   * Stream batch-job progress snapshots as SSE.
   *
   * Each frame is a `BatchPredictionsEvent`-shaped JSON payload (with the
   * per-prediction field stripped server-side; clients fetch the canonical
   * list via `GET /results`). Frames carry both the SSE `id:` (Redis stream
   * msg id) and `event:` (the snapshot's `event` field — `start`,
   * `prediction`, `score`, `finish`).
   *
   * Resumption: clients automatically send `Last-Event-ID` on reconnect;
   * we use it as the `XREAD` start id so no events are missed (provided
   * the stream hasn't been trimmed past it).
   *
   * Heartbeats every ~15s keep proxies from idling the connection out.
   * Synthetic terminal: if Celery reaches a terminal state without a
   * `finish` snapshot reaching Redis, emit one so clients don't hang.
   */
  async streamBatchEvents(
    request:
      operations.StreamBatchPredictionsEventsApiV1JobsBatchPredictionsJobIdEventsGetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsStreamBatchEvents(
      this,
      request,
      options,
    ));
  }

  /**
   * Stream Batch Predictions Results
   *
   * @remarks
   * Stream results for a batch predictions job as application/x-ndjson.
   */
  async streamBatchResults(
    request:
      operations.StreamBatchPredictionsResultsApiV1JobsBatchPredictionsJobIdResultsGetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(jobsStreamBatchResults(
      this,
      request,
      options,
    ));
  }
}
