/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Arbiters } from "./arbiters.js";
import { Chat } from "./chat.js";
import { Examples } from "./examples.js";
import { Jobs } from "./jobs.js";
import { Predictions } from "./predictions.js";

export class ModaicClient extends ClientSDK {
  private _chat?: Chat;
  get chat(): Chat {
    return (this._chat ??= new Chat(this._options));
  }

  private _jobs?: Jobs;
  get jobs(): Jobs {
    return (this._jobs ??= new Jobs(this._options));
  }

  private _arbiters?: Arbiters;
  get arbiters(): Arbiters {
    return (this._arbiters ??= new Arbiters(this._options));
  }

  private _predictions?: Predictions;
  get predictions(): Predictions {
    return (this._predictions ??= new Predictions(this._options));
  }

  private _examples?: Examples;
  get examples(): Examples {
    return (this._examples ??= new Examples(this._options));
  }
}
