/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the modaic SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx createChatCompletionApiV1ChatCompletionsPost.example.ts
 */

import { ModaicClient } from "modaic";

const modaicClient = new ModaicClient({
  token: process.env["MODAIC_TOKEN"] ?? "",
});

async function main() {
  const result = await modaicClient
    .createChatCompletionApiV1ChatCompletionsPost();

  console.log(result);
}

main().catch(console.error);
