/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequest =
  {
    jobId: string;
  };

/** @internal */
export type CancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequest$Outbound =
  {
    job_id: string;
  };

/** @internal */
export const CancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    CancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequest$Outbound,
    CancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequest
  > = z.pipe(
    z.object({
      jobId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        jobId: "job_id",
      });
    }),
  );

export function cancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequestToJSON(
  cancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequest:
    CancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequest,
): string {
  return JSON.stringify(
    CancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequest$outboundSchema
      .parse(
        cancelConfidenceScoreJobApiV1JobsConfidenceScoresJobIdDeleteRequest,
      ),
  );
}
