/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CancelOptimizationJobApiV1JobsGepaJobIdDeleteRequest = {
  jobId: string;
};

/** @internal */
export type CancelOptimizationJobApiV1JobsGepaJobIdDeleteRequest$Outbound = {
  job_id: string;
};

/** @internal */
export const CancelOptimizationJobApiV1JobsGepaJobIdDeleteRequest$outboundSchema:
  z.ZodMiniType<
    CancelOptimizationJobApiV1JobsGepaJobIdDeleteRequest$Outbound,
    CancelOptimizationJobApiV1JobsGepaJobIdDeleteRequest
  > = z.pipe(
    z.object({
      jobId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        jobId: "job_id",
      });
    }),
  );

export function cancelOptimizationJobApiV1JobsGepaJobIdDeleteRequestToJSON(
  cancelOptimizationJobApiV1JobsGepaJobIdDeleteRequest:
    CancelOptimizationJobApiV1JobsGepaJobIdDeleteRequest,
): string {
  return JSON.stringify(
    CancelOptimizationJobApiV1JobsGepaJobIdDeleteRequest$outboundSchema.parse(
      cancelOptimizationJobApiV1JobsGepaJobIdDeleteRequest,
    ),
  );
}
