/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DownloadExportApiV1ExamplesExportDownloadGetRequest = {
  fileKey: string;
  fileName?: string | undefined;
};

/** @internal */
export type DownloadExportApiV1ExamplesExportDownloadGetRequest$Outbound = {
  file_key: string;
  file_name: string;
};

/** @internal */
export const DownloadExportApiV1ExamplesExportDownloadGetRequest$outboundSchema:
  z.ZodMiniType<
    DownloadExportApiV1ExamplesExportDownloadGetRequest$Outbound,
    DownloadExportApiV1ExamplesExportDownloadGetRequest
  > = z.pipe(
    z.object({
      fileKey: z.string(),
      fileName: z._default(z.string(), "export.parquet"),
    }),
    z.transform((v) => {
      return remap$(v, {
        fileKey: "file_key",
        fileName: "file_name",
      });
    }),
  );

export function downloadExportApiV1ExamplesExportDownloadGetRequestToJSON(
  downloadExportApiV1ExamplesExportDownloadGetRequest:
    DownloadExportApiV1ExamplesExportDownloadGetRequest,
): string {
  return JSON.stringify(
    DownloadExportApiV1ExamplesExportDownloadGetRequest$outboundSchema.parse(
      downloadExportApiV1ExamplesExportDownloadGetRequest,
    ),
  );
}
