/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetExampleByIdApiV1ExamplesExampleIdGetRequest = {
  /**
   * The ID of the example
   */
  exampleId: string;
};

/** @internal */
export type GetExampleByIdApiV1ExamplesExampleIdGetRequest$Outbound = {
  example_id: string;
};

/** @internal */
export const GetExampleByIdApiV1ExamplesExampleIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetExampleByIdApiV1ExamplesExampleIdGetRequest$Outbound,
    GetExampleByIdApiV1ExamplesExampleIdGetRequest
  > = z.pipe(
    z.object({
      exampleId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        exampleId: "example_id",
      });
    }),
  );

export function getExampleByIdApiV1ExamplesExampleIdGetRequestToJSON(
  getExampleByIdApiV1ExamplesExampleIdGetRequest:
    GetExampleByIdApiV1ExamplesExampleIdGetRequest,
): string {
  return JSON.stringify(
    GetExampleByIdApiV1ExamplesExampleIdGetRequest$outboundSchema.parse(
      getExampleByIdApiV1ExamplesExampleIdGetRequest,
    ),
  );
}
