/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequest = {
  jobId: string;
};

/** @internal */
export type GetOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequest$Outbound = {
  job_id: string;
};

/** @internal */
export const GetOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequest$outboundSchema:
  z.ZodMiniType<
    GetOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequest$Outbound,
    GetOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequest
  > = z.pipe(
    z.object({
      jobId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        jobId: "job_id",
      });
    }),
  );

export function getOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequestToJSON(
  getOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequest:
    GetOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequest,
): string {
  return JSON.stringify(
    GetOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequest$outboundSchema.parse(
      getOptimizationJobLogsApiV1JobsGepaJobIdLogsGetRequest,
    ),
  );
}
