/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetDistinctHashesApiV1ExamplesDistinctHashesGetRequest = {
  user: string;
  program: string;
};

/** @internal */
export type GetDistinctHashesApiV1ExamplesDistinctHashesGetRequest$Outbound = {
  user: string;
  program: string;
};

/** @internal */
export const GetDistinctHashesApiV1ExamplesDistinctHashesGetRequest$outboundSchema:
  z.ZodMiniType<
    GetDistinctHashesApiV1ExamplesDistinctHashesGetRequest$Outbound,
    GetDistinctHashesApiV1ExamplesDistinctHashesGetRequest
  > = z.object({
    user: z.string(),
    program: z.string(),
  });

export function getDistinctHashesApiV1ExamplesDistinctHashesGetRequestToJSON(
  getDistinctHashesApiV1ExamplesDistinctHashesGetRequest:
    GetDistinctHashesApiV1ExamplesDistinctHashesGetRequest,
): string {
  return JSON.stringify(
    GetDistinctHashesApiV1ExamplesDistinctHashesGetRequest$outboundSchema.parse(
      getDistinctHashesApiV1ExamplesDistinctHashesGetRequest,
    ),
  );
}
