/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetArbiterApiV1ArbitersGetRequest = {
  repo: string;
};

/** @internal */
export type GetArbiterApiV1ArbitersGetRequest$Outbound = {
  repo: string;
};

/** @internal */
export const GetArbiterApiV1ArbitersGetRequest$outboundSchema: z.ZodMiniType<
  GetArbiterApiV1ArbitersGetRequest$Outbound,
  GetArbiterApiV1ArbitersGetRequest
> = z.object({
  repo: z.string(),
});

export function getArbiterApiV1ArbitersGetRequestToJSON(
  getArbiterApiV1ArbitersGetRequest: GetArbiterApiV1ArbitersGetRequest,
): string {
  return JSON.stringify(
    GetArbiterApiV1ArbitersGetRequest$outboundSchema.parse(
      getArbiterApiV1ArbitersGetRequest,
    ),
  );
}
