/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetArbiterSchemaOutputApiV1ArbitersSchemaGetRequest = {
  repo: string;
};

/** @internal */
export type GetArbiterSchemaOutputApiV1ArbitersSchemaGetRequest$Outbound = {
  repo: string;
};

/** @internal */
export const GetArbiterSchemaOutputApiV1ArbitersSchemaGetRequest$outboundSchema:
  z.ZodMiniType<
    GetArbiterSchemaOutputApiV1ArbitersSchemaGetRequest$Outbound,
    GetArbiterSchemaOutputApiV1ArbitersSchemaGetRequest
  > = z.object({
    repo: z.string(),
  });

export function getArbiterSchemaOutputApiV1ArbitersSchemaGetRequestToJSON(
  getArbiterSchemaOutputApiV1ArbitersSchemaGetRequest:
    GetArbiterSchemaOutputApiV1ArbitersSchemaGetRequest,
): string {
  return JSON.stringify(
    GetArbiterSchemaOutputApiV1ArbitersSchemaGetRequest$outboundSchema.parse(
      getArbiterSchemaOutputApiV1ArbitersSchemaGetRequest,
    ),
  );
}
