/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequest =
  {
    jobId: string;
  };

/** @internal */
export type GetConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequest$Outbound =
  {
    job_id: string;
  };

/** @internal */
export const GetConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequest$Outbound,
    GetConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequest
  > = z.pipe(
    z.object({
      jobId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        jobId: "job_id",
      });
    }),
  );

export function getConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequestToJSON(
  getConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequest:
    GetConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequest,
): string {
  return JSON.stringify(
    GetConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequest$outboundSchema
      .parse(
        getConfidenceScoreJobStatusApiV1JobsConfidenceScoresJobIdGetRequest,
      ),
  );
}
