/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetOptimizationJobStatusApiV1JobsGepaJobIdGetRequest = {
  jobId: string;
};

/** @internal */
export type GetOptimizationJobStatusApiV1JobsGepaJobIdGetRequest$Outbound = {
  job_id: string;
};

/** @internal */
export const GetOptimizationJobStatusApiV1JobsGepaJobIdGetRequest$outboundSchema:
  z.ZodMiniType<
    GetOptimizationJobStatusApiV1JobsGepaJobIdGetRequest$Outbound,
    GetOptimizationJobStatusApiV1JobsGepaJobIdGetRequest
  > = z.pipe(
    z.object({
      jobId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        jobId: "job_id",
      });
    }),
  );

export function getOptimizationJobStatusApiV1JobsGepaJobIdGetRequestToJSON(
  getOptimizationJobStatusApiV1JobsGepaJobIdGetRequest:
    GetOptimizationJobStatusApiV1JobsGepaJobIdGetRequest,
): string {
  return JSON.stringify(
    GetOptimizationJobStatusApiV1JobsGepaJobIdGetRequest$outboundSchema.parse(
      getOptimizationJobStatusApiV1JobsGepaJobIdGetRequest,
    ),
  );
}
