/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetGradedCountApiV1ExamplesGradedCountGetRequest = {
  user: string;
  program: string;
};

/** @internal */
export type GetGradedCountApiV1ExamplesGradedCountGetRequest$Outbound = {
  user: string;
  program: string;
};

/** @internal */
export const GetGradedCountApiV1ExamplesGradedCountGetRequest$outboundSchema:
  z.ZodMiniType<
    GetGradedCountApiV1ExamplesGradedCountGetRequest$Outbound,
    GetGradedCountApiV1ExamplesGradedCountGetRequest
  > = z.object({
    user: z.string(),
    program: z.string(),
  });

export function getGradedCountApiV1ExamplesGradedCountGetRequestToJSON(
  getGradedCountApiV1ExamplesGradedCountGetRequest:
    GetGradedCountApiV1ExamplesGradedCountGetRequest,
): string {
  return JSON.stringify(
    GetGradedCountApiV1ExamplesGradedCountGetRequest$outboundSchema.parse(
      getGradedCountApiV1ExamplesGradedCountGetRequest,
    ),
  );
}
