/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Search mode: keyword or semantic
 */
export const SearchMode = {
  Keyword: "keyword",
  Semantic: "semantic",
} as const;
/**
 * Search mode: keyword or semantic
 */
export type SearchMode = ClosedEnum<typeof SearchMode>;

export type ListExamplesApiV1ExamplesGetRequest = {
  user: string;
  program: string;
  page?: number | undefined;
  pageSize?: number | undefined;
  version?: number | null | undefined;
  commitHash?: string | null | undefined;
  /**
   * Comma-separated arbiter hashes to filter by
   */
  commitHashes?: string | null | undefined;
  /**
   * Search across input, output, and ground_truth
   */
  search?: string | null | undefined;
  /**
   * Column to sort by (output, ground_truth, confidence, version, input)
   */
  sortBy?: string | null | undefined;
  /**
   * Sort direction: asc or desc
   */
  sortOrder?: string | undefined;
  /**
   * Only return predictions with confidence below this value
   */
  maxConfidence?: number | null | undefined;
  /**
   * Search mode: keyword or semantic
   */
  searchMode?: SearchMode | undefined;
  /**
   * Hide examples that already have ground truth
   */
  hideGraded?: boolean | undefined;
};

/** @internal */
export const SearchMode$outboundSchema: z.ZodMiniEnum<typeof SearchMode> = z
  .enum(SearchMode);

/** @internal */
export type ListExamplesApiV1ExamplesGetRequest$Outbound = {
  user: string;
  program: string;
  page: number;
  page_size: number;
  version?: number | null | undefined;
  commit_hash?: string | null | undefined;
  commit_hashes?: string | null | undefined;
  search?: string | null | undefined;
  sort_by?: string | null | undefined;
  sort_order: string;
  max_confidence?: number | null | undefined;
  search_mode: string;
  hide_graded: boolean;
};

/** @internal */
export const ListExamplesApiV1ExamplesGetRequest$outboundSchema: z.ZodMiniType<
  ListExamplesApiV1ExamplesGetRequest$Outbound,
  ListExamplesApiV1ExamplesGetRequest
> = z.pipe(
  z.object({
    user: z.string(),
    program: z.string(),
    page: z._default(z.int(), 1),
    pageSize: z._default(z.int(), 30),
    version: z.optional(z.nullable(z.int())),
    commitHash: z.optional(z.nullable(z.string())),
    commitHashes: z.optional(z.nullable(z.string())),
    search: z.optional(z.nullable(z.string())),
    sortBy: z.optional(z.nullable(z.string())),
    sortOrder: z._default(z.string(), "asc"),
    maxConfidence: z.optional(z.nullable(z.number())),
    searchMode: z._default(SearchMode$outboundSchema, "keyword"),
    hideGraded: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      pageSize: "page_size",
      commitHash: "commit_hash",
      commitHashes: "commit_hashes",
      sortBy: "sort_by",
      sortOrder: "sort_order",
      maxConfidence: "max_confidence",
      searchMode: "search_mode",
      hideGraded: "hide_graded",
    });
  }),
);

export function listExamplesApiV1ExamplesGetRequestToJSON(
  listExamplesApiV1ExamplesGetRequest: ListExamplesApiV1ExamplesGetRequest,
): string {
  return JSON.stringify(
    ListExamplesApiV1ExamplesGetRequest$outboundSchema.parse(
      listExamplesApiV1ExamplesGetRequest,
    ),
  );
}
