/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type PatchExampleApiV1ExamplesExampleIdAnnotationPatchRequest = {
  /**
   * The ID of the example
   */
  exampleId: string;
  body?: models.AnnotateExampleRequest | undefined;
};

/** @internal */
export type PatchExampleApiV1ExamplesExampleIdAnnotationPatchRequest$Outbound =
  {
    example_id: string;
    body?: models.AnnotateExampleRequest$Outbound | undefined;
  };

/** @internal */
export const PatchExampleApiV1ExamplesExampleIdAnnotationPatchRequest$outboundSchema:
  z.ZodMiniType<
    PatchExampleApiV1ExamplesExampleIdAnnotationPatchRequest$Outbound,
    PatchExampleApiV1ExamplesExampleIdAnnotationPatchRequest
  > = z.pipe(
    z.object({
      exampleId: z.string(),
      body: z.optional(models.AnnotateExampleRequest$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        exampleId: "example_id",
      });
    }),
  );

export function patchExampleApiV1ExamplesExampleIdAnnotationPatchRequestToJSON(
  patchExampleApiV1ExamplesExampleIdAnnotationPatchRequest:
    PatchExampleApiV1ExamplesExampleIdAnnotationPatchRequest,
): string {
  return JSON.stringify(
    PatchExampleApiV1ExamplesExampleIdAnnotationPatchRequest$outboundSchema
      .parse(patchExampleApiV1ExamplesExampleIdAnnotationPatchRequest),
  );
}
