/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  PredictionAnnotation,
  PredictionAnnotation$Outbound,
  PredictionAnnotation$outboundSchema,
} from "./prediction-annotation.js";

/**
 * Annotate an example with one or more prediction annotations.
 */
export type AnnotateExampleRequest = {
  annotations: Array<PredictionAnnotation>;
};

/** @internal */
export type AnnotateExampleRequest$Outbound = {
  annotations: Array<PredictionAnnotation$Outbound>;
};

/** @internal */
export const AnnotateExampleRequest$outboundSchema: z.ZodMiniType<
  AnnotateExampleRequest$Outbound,
  AnnotateExampleRequest
> = z.object({
  annotations: z.array(PredictionAnnotation$outboundSchema),
});

export function annotateExampleRequestToJSON(
  annotateExampleRequest: AnnotateExampleRequest,
): string {
  return JSON.stringify(
    AnnotateExampleRequest$outboundSchema.parse(annotateExampleRequest),
  );
}
