/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ArbiterRequest = {
  arbiterRepo: string;
  arbiterRevision?: string | undefined;
  groundTruth?: string | null | undefined;
  groundReasoning?: string | undefined;
};

/** @internal */
export type ArbiterRequest$Outbound = {
  arbiter_repo: string;
  arbiter_revision: string;
  ground_truth?: string | null | undefined;
  ground_reasoning: string;
};

/** @internal */
export const ArbiterRequest$outboundSchema: z.ZodMiniType<
  ArbiterRequest$Outbound,
  ArbiterRequest
> = z.pipe(
  z.object({
    arbiterRepo: z.string(),
    arbiterRevision: z._default(z.string(), "main"),
    groundTruth: z.optional(z.nullable(z.string())),
    groundReasoning: z._default(z.string(), ""),
  }),
  z.transform((v) => {
    return remap$(v, {
      arbiterRepo: "arbiter_repo",
      arbiterRevision: "arbiter_revision",
      groundTruth: "ground_truth",
      groundReasoning: "ground_reasoning",
    });
  }),
);

export function arbiterRequestToJSON(arbiterRequest: ArbiterRequest): string {
  return JSON.stringify(ArbiterRequest$outboundSchema.parse(arbiterRequest));
}
