/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const BatchExampleSplit = {
  Train: "train",
  Test: "test",
  None: "none",
} as const;
export type BatchExampleSplit = ClosedEnum<typeof BatchExampleSplit>;

/**
 * One row in a batch predictions request.
 *
 * @remarks
 *
 * Split contract (mirrors `examples/schemas.py::PredictedExample`):
 * only `"train"` and `"test"` are valid downstream — `"none"` exists
 * purely as the storage marker for unannotated rows. Callers MUST NOT
 * send `"none"` explicitly; omit `split` instead and let `get_split`
 * randomly assign train/test (80/20) when `ground_truth` is provided.
 * Without that auto-assignment, annotated batch rows would land in
 * ClickHouse with `split='none'` and be skipped by every downstream
 * consumer (GEPA, scoring, dataset export).
 */
export type BatchExample = {
  input: { [k: string]: any };
  altId?: string | null | undefined;
  groundTruth?: { [k: string]: any } | null | undefined;
  groundReasoning?: string | undefined;
  split?: BatchExampleSplit | null | undefined;
};

/** @internal */
export const BatchExampleSplit$outboundSchema: z.ZodMiniEnum<
  typeof BatchExampleSplit
> = z.enum(BatchExampleSplit);

/** @internal */
export type BatchExample$Outbound = {
  input: { [k: string]: any };
  alt_id?: string | null | undefined;
  ground_truth?: { [k: string]: any } | null | undefined;
  ground_reasoning: string;
  split?: string | null | undefined;
};

/** @internal */
export const BatchExample$outboundSchema: z.ZodMiniType<
  BatchExample$Outbound,
  BatchExample
> = z.pipe(
  z.object({
    input: z.record(z.string(), z.any()),
    altId: z.optional(z.nullable(z.string())),
    groundTruth: z.optional(z.nullable(z.record(z.string(), z.any()))),
    groundReasoning: z._default(z.string(), ""),
    split: z.optional(z.nullable(BatchExampleSplit$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      altId: "alt_id",
      groundTruth: "ground_truth",
      groundReasoning: "ground_reasoning",
    });
  }),
);

export function batchExampleToJSON(batchExample: BatchExample): string {
  return JSON.stringify(BatchExample$outboundSchema.parse(batchExample));
}
