/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type BatchArbiter = {
  arbiterRepo: string;
  arbiterRevision?: string | undefined;
};

/** @internal */
export type BatchArbiter$Outbound = {
  arbiter_repo: string;
  arbiter_revision: string;
};

/** @internal */
export const BatchArbiter$outboundSchema: z.ZodMiniType<
  BatchArbiter$Outbound,
  BatchArbiter
> = z.pipe(
  z.object({
    arbiterRepo: z.string(),
    arbiterRevision: z._default(z.string(), "main"),
  }),
  z.transform((v) => {
    return remap$(v, {
      arbiterRepo: "arbiter_repo",
      arbiterRevision: "arbiter_revision",
    });
  }),
);

export function batchArbiterToJSON(batchArbiter: BatchArbiter): string {
  return JSON.stringify(BatchArbiter$outboundSchema.parse(batchArbiter));
}
