/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ChatCompletionChoice,
  ChatCompletionChoice$inboundSchema,
} from "./chat-completion-choice.js";
import {
  CompletionUsage,
  CompletionUsage$inboundSchema,
} from "./completion-usage.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ChatCompletionResponse = {
  id?: string | undefined;
  object: string;
  created?: number | undefined;
  model: string;
  choices: Array<ChatCompletionChoice>;
  usage: CompletionUsage;
  systemFingerprint?: string | null | undefined;
};

/** @internal */
export const ChatCompletionResponse$inboundSchema: z.ZodMiniType<
  ChatCompletionResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    object: z._default(types.string(), "chat.completion"),
    created: types.optional(types.number()),
    model: types.string(),
    choices: z.array(ChatCompletionChoice$inboundSchema),
    usage: CompletionUsage$inboundSchema,
    system_fingerprint: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "system_fingerprint": "systemFingerprint",
    });
  }),
);

export function chatCompletionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionResponse' from JSON`,
  );
}
