/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import {
  ChatMessage,
  ChatMessage$Outbound,
  ChatMessage$outboundSchema,
} from "./chat-message.js";

export type Stop = string | Array<string>;

export type ChatCompletionRequest = {
  model: string;
  messages: Array<ChatMessage>;
  temperature?: number | null | undefined;
  topP?: number | null | undefined;
  n?: number | null | undefined;
  stream?: boolean | null | undefined;
  stop?: string | Array<string> | null | undefined;
  maxTokens?: number | null | undefined;
  presencePenalty?: number | null | undefined;
  frequencyPenalty?: number | null | undefined;
  logitBias?: { [k: string]: number } | null | undefined;
  user?: string | null | undefined;
};

/** @internal */
export type Stop$Outbound = string | Array<string>;

/** @internal */
export const Stop$outboundSchema: z.ZodMiniType<Stop$Outbound, Stop> =
  smartUnion([z.string(), z.array(z.string())]);

export function stopToJSON(stop: Stop): string {
  return JSON.stringify(Stop$outboundSchema.parse(stop));
}

/** @internal */
export type ChatCompletionRequest$Outbound = {
  model: string;
  messages: Array<ChatMessage$Outbound>;
  temperature?: number | null | undefined;
  top_p?: number | null | undefined;
  n?: number | null | undefined;
  stream?: boolean | null | undefined;
  stop?: string | Array<string> | null | undefined;
  max_tokens?: number | null | undefined;
  presence_penalty?: number | null | undefined;
  frequency_penalty?: number | null | undefined;
  logit_bias?: { [k: string]: number } | null | undefined;
  user?: string | null | undefined;
};

/** @internal */
export const ChatCompletionRequest$outboundSchema: z.ZodMiniType<
  ChatCompletionRequest$Outbound,
  ChatCompletionRequest
> = z.pipe(
  z.object({
    model: z.string(),
    messages: z.array(ChatMessage$outboundSchema),
    temperature: z.optional(z.nullable(z.number())),
    topP: z.optional(z.nullable(z.number())),
    n: z.optional(z.nullable(z.int())),
    stream: z.optional(z.nullable(z.boolean())),
    stop: z.optional(z.nullable(smartUnion([z.string(), z.array(z.string())]))),
    maxTokens: z.optional(z.nullable(z.int())),
    presencePenalty: z.optional(z.nullable(z.number())),
    frequencyPenalty: z.optional(z.nullable(z.number())),
    logitBias: z.optional(z.nullable(z.record(z.string(), z.number()))),
    user: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      topP: "top_p",
      maxTokens: "max_tokens",
      presencePenalty: "presence_penalty",
      frequencyPenalty: "frequency_penalty",
      logitBias: "logit_bias",
    });
  }),
);

export function chatCompletionRequestToJSON(
  chatCompletionRequest: ChatCompletionRequest,
): string {
  return JSON.stringify(
    ChatCompletionRequest$outboundSchema.parse(chatCompletionRequest),
  );
}
