/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ChatMessage, ChatMessage$inboundSchema } from "./chat-message.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ChatCompletionChoice = {
  index: number;
  message: ChatMessage;
  finishReason?: string | null | undefined;
};

/** @internal */
export const ChatCompletionChoice$inboundSchema: z.ZodMiniType<
  ChatCompletionChoice,
  unknown
> = z.pipe(
  z.object({
    index: types.number(),
    message: ChatMessage$inboundSchema,
    finish_reason: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "finish_reason": "finishReason",
    });
  }),
);

export function chatCompletionChoiceFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionChoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionChoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionChoice' from JSON`,
  );
}
