/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ChatMessage = {
  role: string;
  content: string;
  name?: string | null | undefined;
  toolCalls?: Array<{ [k: string]: any }> | null | undefined;
};

/** @internal */
export const ChatMessage$inboundSchema: z.ZodMiniType<ChatMessage, unknown> = z
  .pipe(
    z.object({
      role: types.string(),
      content: types.string(),
      name: z.optional(z.nullable(types.string())),
      tool_calls: z.optional(
        z.nullable(z.array(z.record(z.string(), z.any()))),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "tool_calls": "toolCalls",
      });
    }),
  );
/** @internal */
export type ChatMessage$Outbound = {
  role: string;
  content: string;
  name?: string | null | undefined;
  tool_calls?: Array<{ [k: string]: any }> | null | undefined;
};

/** @internal */
export const ChatMessage$outboundSchema: z.ZodMiniType<
  ChatMessage$Outbound,
  ChatMessage
> = z.pipe(
  z.object({
    role: z.string(),
    content: z.string(),
    name: z.optional(z.nullable(z.string())),
    toolCalls: z.optional(z.nullable(z.array(z.record(z.string(), z.any())))),
  }),
  z.transform((v) => {
    return remap$(v, {
      toolCalls: "tool_calls",
    });
  }),
);

export function chatMessageToJSON(chatMessage: ChatMessage): string {
  return JSON.stringify(ChatMessage$outboundSchema.parse(chatMessage));
}
export function chatMessageFromJSON(
  jsonString: string,
): SafeParseResult<ChatMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatMessage' from JSON`,
  );
}
