/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type CompletionUsage = {
  promptTokens: number | null;
  completionTokens: number | null;
  totalTokens: number | null;
};

/** @internal */
export const CompletionUsage$inboundSchema: z.ZodMiniType<
  CompletionUsage,
  unknown
> = z.pipe(
  z.object({
    prompt_tokens: types.nullable(types.number()),
    completion_tokens: types.nullable(types.number()),
    total_tokens: types.nullable(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "prompt_tokens": "promptTokens",
      "completion_tokens": "completionTokens",
      "total_tokens": "totalTokens",
    });
  }),
);

export function completionUsageFromJSON(
  jsonString: string,
): SafeParseResult<CompletionUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionUsage' from JSON`,
  );
}
