/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ConfidenceStatusResponseStatus = {
  Queued: "queued",
  Completed: "completed",
  Failed: "failed",
} as const;
export type ConfidenceStatusResponseStatus = OpenEnum<
  typeof ConfidenceStatusResponseStatus
>;

export type ConfidenceStatusResponse = {
  status: ConfidenceStatusResponseStatus;
  predictionId: string;
  score?: number | null | undefined;
  error?: string | null | undefined;
};

/** @internal */
export const ConfidenceStatusResponseStatus$inboundSchema: z.ZodMiniType<
  ConfidenceStatusResponseStatus,
  unknown
> = openEnums.inboundSchema(ConfidenceStatusResponseStatus);

/** @internal */
export const ConfidenceStatusResponse$inboundSchema: z.ZodMiniType<
  ConfidenceStatusResponse,
  unknown
> = z.pipe(
  z.object({
    status: ConfidenceStatusResponseStatus$inboundSchema,
    prediction_id: types.string(),
    score: z.optional(z.nullable(types.number())),
    error: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "prediction_id": "predictionId",
    });
  }),
);

export function confidenceStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConfidenceStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConfidenceStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConfidenceStatusResponse' from JSON`,
  );
}
