/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type ConfidenceScoreJobRequest = {
  arbiterRepo: string;
};

/** @internal */
export type ConfidenceScoreJobRequest$Outbound = {
  arbiter_repo: string;
};

/** @internal */
export const ConfidenceScoreJobRequest$outboundSchema: z.ZodMiniType<
  ConfidenceScoreJobRequest$Outbound,
  ConfidenceScoreJobRequest
> = z.pipe(
  z.object({
    arbiterRepo: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      arbiterRepo: "arbiter_repo",
    });
  }),
);

export function confidenceScoreJobRequestToJSON(
  confidenceScoreJobRequest: ConfidenceScoreJobRequest,
): string {
  return JSON.stringify(
    ConfidenceScoreJobRequest$outboundSchema.parse(confidenceScoreJobRequest),
  );
}
