/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Delete one or more examples from a repo.
 */
export type DeleteExamplesRequest = {
  exampleIds: Array<string>;
  arbiterRepo: string;
};

/** @internal */
export type DeleteExamplesRequest$Outbound = {
  example_ids: Array<string>;
  arbiter_repo: string;
};

/** @internal */
export const DeleteExamplesRequest$outboundSchema: z.ZodMiniType<
  DeleteExamplesRequest$Outbound,
  DeleteExamplesRequest
> = z.pipe(
  z.object({
    exampleIds: z.array(z.string()),
    arbiterRepo: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      exampleIds: "example_ids",
      arbiterRepo: "arbiter_repo",
    });
  }),
);

export function deleteExamplesRequestToJSON(
  deleteExamplesRequest: DeleteExamplesRequest,
): string {
  return JSON.stringify(
    DeleteExamplesRequest$outboundSchema.parse(deleteExamplesRequest),
  );
}
