/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * A presigned parquet download for exported examples.
 */
export type ExportExamplesResponse = {
  downloadUrl: string;
  fileKey: string;
  fileName: string;
  expiresIn: number;
  rowCount: number;
};

/** @internal */
export const ExportExamplesResponse$inboundSchema: z.ZodMiniType<
  ExportExamplesResponse,
  unknown
> = z.pipe(
  z.object({
    download_url: types.string(),
    file_key: types.string(),
    file_name: types.string(),
    expires_in: types.number(),
    row_count: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "download_url": "downloadUrl",
      "file_key": "fileKey",
      "file_name": "fileName",
      "expires_in": "expiresIn",
      "row_count": "rowCount",
    });
  }),
);

export function exportExamplesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExportExamplesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExportExamplesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExportExamplesResponse' from JSON`,
  );
}
