/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Export examples and predictions for a repo.
 */
export type ExportExamplesRequest = {
  arbiterRepo: string;
};

/** @internal */
export type ExportExamplesRequest$Outbound = {
  arbiter_repo: string;
};

/** @internal */
export const ExportExamplesRequest$outboundSchema: z.ZodMiniType<
  ExportExamplesRequest$Outbound,
  ExportExamplesRequest
> = z.pipe(
  z.object({
    arbiterRepo: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      arbiterRepo: "arbiter_repo",
    });
  }),
);

export function exportExamplesRequestToJSON(
  exportExamplesRequest: ExportExamplesRequest,
): string {
  return JSON.stringify(
    ExportExamplesRequest$outboundSchema.parse(exportExamplesRequest),
  );
}
