/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type FieldSchema = {
  name: string;
  type: string;
  allowedValues?: Array<any> | null | undefined;
  objectSchema?: { [k: string]: any } | null | undefined;
  nullable?: boolean | undefined;
  description?: string | null | undefined;
};

/** @internal */
export type FieldSchema$Outbound = {
  name: string;
  type: string;
  allowed_values?: Array<any> | null | undefined;
  object_schema?: { [k: string]: any } | null | undefined;
  nullable: boolean;
  description?: string | null | undefined;
};

/** @internal */
export const FieldSchema$outboundSchema: z.ZodMiniType<
  FieldSchema$Outbound,
  FieldSchema
> = z.pipe(
  z.object({
    name: z.string(),
    type: z.string(),
    allowedValues: z.optional(z.nullable(z.array(z.any()))),
    objectSchema: z.optional(z.nullable(z.record(z.string(), z.any()))),
    nullable: z._default(z.boolean(), false),
    description: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      allowedValues: "allowed_values",
      objectSchema: "object_schema",
    });
  }),
);

export function fieldSchemaToJSON(fieldSchema: FieldSchema): string {
  return JSON.stringify(FieldSchema$outboundSchema.parse(fieldSchema));
}
