/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { Lm, Lm$Outbound, Lm$outboundSchema } from "./lm.js";

export const Auto = {
  Light: "light",
  Medium: "medium",
  Heavy: "heavy",
} as const;
export type Auto = ClosedEnum<typeof Auto>;

export const CandidateSelectionStrategy = {
  Pareto: "pareto",
  CurrentBest: "current_best",
} as const;
export type CandidateSelectionStrategy = ClosedEnum<
  typeof CandidateSelectionStrategy
>;

export const ComponentSelector = {
  RoundRobin: "round_robin",
  All: "all",
} as const;
export type ComponentSelector = ClosedEnum<typeof ComponentSelector>;

export type GepaKwargs = {
  auto?: Auto | null | undefined;
  maxFullEvals?: number | null | undefined;
  maxMetricCalls?: number | null | undefined;
  reflectionMinibatchSize?: number | undefined;
  candidateSelectionStrategy?: CandidateSelectionStrategy | undefined;
  reflectionLm?: Lm | null | undefined;
  skipPerfectScore?: boolean | undefined;
  addFormatFailureAsFeedback?: boolean | undefined;
  componentSelector?: ComponentSelector | undefined;
  useMerge?: boolean | undefined;
  maxMergeInvocations?: number | null | undefined;
  seed?: number | null | undefined;
  gepaKwargs?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const Auto$outboundSchema: z.ZodMiniEnum<typeof Auto> = z.enum(Auto);

/** @internal */
export const CandidateSelectionStrategy$outboundSchema: z.ZodMiniEnum<
  typeof CandidateSelectionStrategy
> = z.enum(CandidateSelectionStrategy);

/** @internal */
export const ComponentSelector$outboundSchema: z.ZodMiniEnum<
  typeof ComponentSelector
> = z.enum(ComponentSelector);

/** @internal */
export type GepaKwargs$Outbound = {
  auto?: string | null | undefined;
  max_full_evals?: number | null | undefined;
  max_metric_calls?: number | null | undefined;
  reflection_minibatch_size: number;
  candidate_selection_strategy: string;
  reflection_lm?: Lm$Outbound | null | undefined;
  skip_perfect_score: boolean;
  add_format_failure_as_feedback: boolean;
  component_selector: string;
  use_merge: boolean;
  max_merge_invocations?: number | null | undefined;
  seed?: number | null | undefined;
  gepa_kwargs?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const GepaKwargs$outboundSchema: z.ZodMiniType<
  GepaKwargs$Outbound,
  GepaKwargs
> = z.pipe(
  z.object({
    auto: z.optional(z.nullable(Auto$outboundSchema)),
    maxFullEvals: z.optional(z.nullable(z.int())),
    maxMetricCalls: z.optional(z.nullable(z.int())),
    reflectionMinibatchSize: z._default(z.int(), 3),
    candidateSelectionStrategy: z._default(
      CandidateSelectionStrategy$outboundSchema,
      "pareto",
    ),
    reflectionLm: z.optional(z.nullable(Lm$outboundSchema)),
    skipPerfectScore: z._default(z.boolean(), true),
    addFormatFailureAsFeedback: z._default(z.boolean(), false),
    componentSelector: z._default(
      ComponentSelector$outboundSchema,
      "round_robin",
    ),
    useMerge: z._default(z.boolean(), true),
    maxMergeInvocations: z.optional(z.nullable(z.int())),
    seed: z.optional(z.nullable(z.int())),
    gepaKwargs: z.optional(z.nullable(z.record(z.string(), z.any()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      maxFullEvals: "max_full_evals",
      maxMetricCalls: "max_metric_calls",
      reflectionMinibatchSize: "reflection_minibatch_size",
      candidateSelectionStrategy: "candidate_selection_strategy",
      reflectionLm: "reflection_lm",
      skipPerfectScore: "skip_perfect_score",
      addFormatFailureAsFeedback: "add_format_failure_as_feedback",
      componentSelector: "component_selector",
      useMerge: "use_merge",
      maxMergeInvocations: "max_merge_invocations",
      gepaKwargs: "gepa_kwargs",
    });
  }),
);

export function gepaKwargsToJSON(gepaKwargs: GepaKwargs): string {
  return JSON.stringify(GepaKwargs$outboundSchema.parse(gepaKwargs));
}
