/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  GepaKwargs,
  GepaKwargs$Outbound,
  GepaKwargs$outboundSchema,
} from "./gepa-kwargs.js";

export type GepaJobRequest = {
  arbiterRepo: string;
  arbiterRevision?: string | undefined;
  pushBranch?: string | undefined;
  pushTag?: string | null | undefined;
  gepaKwargs?: GepaKwargs | undefined;
};

/** @internal */
export type GepaJobRequest$Outbound = {
  arbiter_repo: string;
  arbiter_revision: string;
  push_branch: string;
  push_tag?: string | null | undefined;
  gepa_kwargs?: GepaKwargs$Outbound | undefined;
};

/** @internal */
export const GepaJobRequest$outboundSchema: z.ZodMiniType<
  GepaJobRequest$Outbound,
  GepaJobRequest
> = z.pipe(
  z.object({
    arbiterRepo: z.string(),
    arbiterRevision: z._default(z.string(), "main"),
    pushBranch: z._default(z.string(), "main"),
    pushTag: z.optional(z.nullable(z.string())),
    gepaKwargs: z.optional(GepaKwargs$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      arbiterRepo: "arbiter_repo",
      arbiterRevision: "arbiter_revision",
      pushBranch: "push_branch",
      pushTag: "push_tag",
      gepaKwargs: "gepa_kwargs",
    });
  }),
);

export function gepaJobRequestToJSON(gepaJobRequest: GepaJobRequest): string {
  return JSON.stringify(GepaJobRequest$outboundSchema.parse(gepaJobRequest));
}
