/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GepaJobResponseStatus = {
  InProgress: "in_progress",
  Completed: "completed",
  Failed: "failed",
} as const;
export type GepaJobResponseStatus = OpenEnum<typeof GepaJobResponseStatus>;

export const Phase = {
  Optimizing: "optimizing",
  Finalizing: "finalizing",
  RePredicting: "re_predicting",
  Scoring: "scoring",
  Tuning: "tuning",
  Done: "done",
} as const;
export type Phase = OpenEnum<typeof Phase>;

export type GepaJobResponse = {
  jobId: string;
  status: GepaJobResponseStatus;
  message?: string | null | undefined;
  results?: { [k: string]: any } | null | undefined;
  phase?: Phase | null | undefined;
  commitHash?: string | null | undefined;
};

/** @internal */
export const GepaJobResponseStatus$inboundSchema: z.ZodMiniType<
  GepaJobResponseStatus,
  unknown
> = openEnums.inboundSchema(GepaJobResponseStatus);

/** @internal */
export const Phase$inboundSchema: z.ZodMiniType<Phase, unknown> = openEnums
  .inboundSchema(Phase);

/** @internal */
export const GepaJobResponse$inboundSchema: z.ZodMiniType<
  GepaJobResponse,
  unknown
> = z.pipe(
  z.object({
    job_id: types.string(),
    status: GepaJobResponseStatus$inboundSchema,
    message: z.optional(z.nullable(types.string())),
    results: z.optional(z.nullable(z.record(z.string(), z.any()))),
    phase: z.optional(z.nullable(Phase$inboundSchema)),
    commit_hash: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "job_id": "jobId",
      "commit_hash": "commitHash",
    });
  }),
);

export function gepaJobResponseFromJSON(
  jsonString: string,
): SafeParseResult<GepaJobResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GepaJobResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GepaJobResponse' from JSON`,
  );
}
