/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type GetConfidenceRequest = {
  arbiterRepo: string;
  predictionId?: string | null | undefined;
  messages: Array<{ [k: string]: any }>;
};

/** @internal */
export type GetConfidenceRequest$Outbound = {
  arbiter_repo: string;
  prediction_id?: string | null | undefined;
  messages: Array<{ [k: string]: any }>;
};

/** @internal */
export const GetConfidenceRequest$outboundSchema: z.ZodMiniType<
  GetConfidenceRequest$Outbound,
  GetConfidenceRequest
> = z.pipe(
  z.object({
    arbiterRepo: z.string(),
    predictionId: z.optional(z.nullable(z.string())),
    messages: z.array(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      arbiterRepo: "arbiter_repo",
      predictionId: "prediction_id",
    });
  }),
);

export function getConfidenceRequestToJSON(
  getConfidenceRequest: GetConfidenceRequest,
): string {
  return JSON.stringify(
    GetConfidenceRequest$outboundSchema.parse(getConfidenceRequest),
  );
}
