/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  FieldSchema,
  FieldSchema$Outbound,
  FieldSchema$outboundSchema,
} from "./field-schema.js";

export type InitArbiterRequest = {
  repo: string;
  inputs: Array<FieldSchema>;
  outputs: Array<FieldSchema>;
  instructions?: string | null | undefined;
  model?: string | undefined;
  baseUrl?: string | null | undefined;
};

/** @internal */
export type InitArbiterRequest$Outbound = {
  repo: string;
  inputs: Array<FieldSchema$Outbound>;
  outputs: Array<FieldSchema$Outbound>;
  instructions?: string | null | undefined;
  model: string;
  base_url?: string | null | undefined;
};

/** @internal */
export const InitArbiterRequest$outboundSchema: z.ZodMiniType<
  InitArbiterRequest$Outbound,
  InitArbiterRequest
> = z.pipe(
  z.object({
    repo: z.string(),
    inputs: z.array(FieldSchema$outboundSchema),
    outputs: z.array(FieldSchema$outboundSchema),
    instructions: z.optional(z.nullable(z.string())),
    model: z._default(z.string(), "qwen3-vl-32b-instruct"),
    baseUrl: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      baseUrl: "base_url",
    });
  }),
);

export function initArbiterRequestToJSON(
  initArbiterRequest: InitArbiterRequest,
): string {
  return JSON.stringify(
    InitArbiterRequest$outboundSchema.parse(initArbiterRequest),
  );
}
