/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type Lm = {
  model: string;
  kwargs?: { [k: string]: any } | null | undefined;
};

/** @internal */
export type Lm$Outbound = {
  model: string;
  kwargs?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const Lm$outboundSchema: z.ZodMiniType<Lm$Outbound, Lm> = z.object({
  model: z.string(),
  kwargs: z.optional(z.nullable(z.record(z.string(), z.any()))),
});

export function lmToJSON(lm: Lm): string {
  return JSON.stringify(Lm$outboundSchema.parse(lm));
}
