/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PredictedExample,
  PredictedExample$inboundSchema,
} from "./predicted-example.js";

export type PaginatedPage = {
  items: Array<PredictedExample>;
  total: number;
  unfilteredTotal: number;
  page: number;
  pageSize: number;
  totalPages: number;
};

/** @internal */
export const PaginatedPage$inboundSchema: z.ZodMiniType<
  PaginatedPage,
  unknown
> = z.pipe(
  z.object({
    items: z.array(PredictedExample$inboundSchema),
    total: types.number(),
    unfiltered_total: types.number(),
    page: types.number(),
    page_size: types.number(),
    total_pages: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "unfiltered_total": "unfilteredTotal",
      "page_size": "pageSize",
      "total_pages": "totalPages",
    });
  }),
);

export function paginatedPageFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedPage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedPage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedPage' from JSON`,
  );
}
