/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Input = { [k: string]: any } | string;

export const PredictedExampleSplit = {
  Train: "train",
  Test: "test",
  None: "none",
} as const;
export type PredictedExampleSplit = OpenEnum<typeof PredictedExampleSplit>;

/**
 * A predicted example from a arbiter.
 *
 * @remarks
 * Used for both ingestion (POST) and retrieval (GET) of examples.
 *
 * Split contract: `"none"` is the ClickHouse marker for unannotated
 * rows. Callers MUST NOT send `"none"` explicitly — omit `split` and
 * let `get_split` decide. When `ground_truth` is set, `get_split`
 * randomly assigns train/test (80/20); when it isn't, split is forced
 * to `"none"`. Downstream consumers (GEPA, scoring, dataset export)
 * filter on `split in ('train','test')`, so a row stuck at `"none"`
 * is invisible to them. The same rule lives on
 * `jobs/schemas.py::BatchExample`; if you change one, change the other.
 */
export type PredictedExample = {
  id?: string | null | undefined;
  altId?: string | null | undefined;
  arbiterRepo: string;
  arbiterHash: string;
  input?: { [k: string]: any } | string | null | undefined;
  groundTruth?: string | null | undefined;
  groundReasoning: string;
  messages?: Array<{ [k: string]: any }> | null | undefined;
  serializedOutput?: string | null | undefined;
  reasoning?: string | null | undefined;
  error: string;
  split?: PredictedExampleSplit | null | undefined;
  version?: number | null | undefined;
  predictionTimestamp?: Date | undefined;
  confidence?: number | null | undefined;
};

/** @internal */
export const Input$inboundSchema: z.ZodMiniType<Input, unknown> = smartUnion([
  z.record(z.string(), z.any()),
  types.string(),
]);

export function inputFromJSON(
  jsonString: string,
): SafeParseResult<Input, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Input$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Input' from JSON`,
  );
}

/** @internal */
export const PredictedExampleSplit$inboundSchema: z.ZodMiniType<
  PredictedExampleSplit,
  unknown
> = openEnums.inboundSchema(PredictedExampleSplit);

/** @internal */
export const PredictedExample$inboundSchema: z.ZodMiniType<
  PredictedExample,
  unknown
> = z.pipe(
  z.object({
    id: z.optional(z.nullable(types.string())),
    alt_id: z.optional(z.nullable(types.string())),
    arbiter_repo: types.string(),
    arbiter_hash: z._default(types.string(), ""),
    input: z.optional(
      z.nullable(smartUnion([z.record(z.string(), z.any()), types.string()])),
    ),
    ground_truth: z.optional(z.nullable(types.string())),
    ground_reasoning: z._default(types.string(), ""),
    messages: z.optional(z.nullable(z.array(z.record(z.string(), z.any())))),
    serialized_output: z.optional(z.nullable(types.string())),
    reasoning: z.optional(z.nullable(types.string())),
    error: z._default(types.string(), ""),
    split: z.optional(z.nullable(PredictedExampleSplit$inboundSchema)),
    version: z.optional(z.nullable(types.number())),
    prediction_timestamp: types.optional(types.date()),
    confidence: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "alt_id": "altId",
      "arbiter_repo": "arbiterRepo",
      "arbiter_hash": "arbiterHash",
      "ground_truth": "groundTruth",
      "ground_reasoning": "groundReasoning",
      "serialized_output": "serializedOutput",
      "prediction_timestamp": "predictionTimestamp",
    });
  }),
);

export function predictedExampleFromJSON(
  jsonString: string,
): SafeParseResult<PredictedExample, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PredictedExample$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PredictedExample' from JSON`,
  );
}
