/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ArbiterRequest,
  ArbiterRequest$Outbound,
  ArbiterRequest$outboundSchema,
} from "./arbiter-request.js";

export type SrcApiV1ArbitersSchemasPredictExampleRequest = {
  input: { [k: string]: any };
  altId?: string | null | undefined;
  arbiters: Array<ArbiterRequest>;
};

/** @internal */
export type SrcApiV1ArbitersSchemasPredictExampleRequest$Outbound = {
  input: { [k: string]: any };
  alt_id?: string | null | undefined;
  arbiters: Array<ArbiterRequest$Outbound>;
};

/** @internal */
export const SrcApiV1ArbitersSchemasPredictExampleRequest$outboundSchema:
  z.ZodMiniType<
    SrcApiV1ArbitersSchemasPredictExampleRequest$Outbound,
    SrcApiV1ArbitersSchemasPredictExampleRequest
  > = z.pipe(
    z.object({
      input: z.record(z.string(), z.any()),
      altId: z.optional(z.nullable(z.string())),
      arbiters: z.array(ArbiterRequest$outboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        altId: "alt_id",
      });
    }),
  );

export function srcApiV1ArbitersSchemasPredictExampleRequestToJSON(
  srcApiV1ArbitersSchemasPredictExampleRequest:
    SrcApiV1ArbitersSchemasPredictExampleRequest,
): string {
  return JSON.stringify(
    SrcApiV1ArbitersSchemasPredictExampleRequest$outboundSchema.parse(
      srcApiV1ArbitersSchemasPredictExampleRequest,
    ),
  );
}
