/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * v2 single-arbiter, single-example prediction request.
 *
 * @remarks
 *
 * Differs from v1 ``PredictExampleRequest`` (which takes a list of arbiters)
 * by accepting exactly one arbiter and putting ground-truth on the example
 * rather than on the arbiter entry.
 */
export type SrcApiV2ArbitersSchemasPredictExampleRequest = {
  input: { [k: string]: any };
  altId?: string | null | undefined;
  arbiterRepo: string;
  arbiterRevision?: string | undefined;
  groundTruth?: { [k: string]: any } | null | undefined;
  groundReasoning?: string | undefined;
  computeConfidence?: boolean | undefined;
};

/** @internal */
export type SrcApiV2ArbitersSchemasPredictExampleRequest$Outbound = {
  input: { [k: string]: any };
  alt_id?: string | null | undefined;
  arbiter_repo: string;
  arbiter_revision: string;
  ground_truth?: { [k: string]: any } | null | undefined;
  ground_reasoning: string;
  compute_confidence: boolean;
};

/** @internal */
export const SrcApiV2ArbitersSchemasPredictExampleRequest$outboundSchema:
  z.ZodMiniType<
    SrcApiV2ArbitersSchemasPredictExampleRequest$Outbound,
    SrcApiV2ArbitersSchemasPredictExampleRequest
  > = z.pipe(
    z.object({
      input: z.record(z.string(), z.any()),
      altId: z.optional(z.nullable(z.string())),
      arbiterRepo: z.string(),
      arbiterRevision: z._default(z.string(), "main"),
      groundTruth: z.optional(z.nullable(z.record(z.string(), z.any()))),
      groundReasoning: z._default(z.string(), ""),
      computeConfidence: z._default(z.boolean(), false),
    }),
    z.transform((v) => {
      return remap$(v, {
        altId: "alt_id",
        arbiterRepo: "arbiter_repo",
        arbiterRevision: "arbiter_revision",
        groundTruth: "ground_truth",
        groundReasoning: "ground_reasoning",
        computeConfidence: "compute_confidence",
      });
    }),
  );

export function srcApiV2ArbitersSchemasPredictExampleRequestToJSON(
  srcApiV2ArbitersSchemasPredictExampleRequest:
    SrcApiV2ArbitersSchemasPredictExampleRequest,
): string {
  return JSON.stringify(
    SrcApiV2ArbitersSchemasPredictExampleRequest$outboundSchema.parse(
      srcApiV2ArbitersSchemasPredictExampleRequest,
    ),
  );
}
