/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateArbiterMetadataRequest = {
  repo: string;
  metadata: { [k: string]: any };
};

/** @internal */
export type UpdateArbiterMetadataRequest$Outbound = {
  repo: string;
  metadata: { [k: string]: any };
};

/** @internal */
export const UpdateArbiterMetadataRequest$outboundSchema: z.ZodMiniType<
  UpdateArbiterMetadataRequest$Outbound,
  UpdateArbiterMetadataRequest
> = z.object({
  repo: z.string(),
  metadata: z.record(z.string(), z.any()),
});

export function updateArbiterMetadataRequestToJSON(
  updateArbiterMetadataRequest: UpdateArbiterMetadataRequest,
): string {
  return JSON.stringify(
    UpdateArbiterMetadataRequest$outboundSchema.parse(
      updateArbiterMetadataRequest,
    ),
  );
}
